version: '3'
services:
  mongo:
     image: localhost:5000/mongo	
     volumes:
     - data:/data/mongodb
     container_name: mongodb-service
     ports:
     - 27017:27017
     networks:
     - netMongo

  backend:
     image: localhost:5000/backend-v1
     container_name: backend
     ports:
     - 5001:5001
     networks:
     - netMongo

  frontend:
     image: localhost:5000/frontend-v1
     container_name: frontend
     ports:
     - 3001:80
     networks:
     - netMongo

volumes:
   data:
networks:
  netMongo:
    driver: bridge